// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nukycztwlruakrzthlyw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51a3ljenR3bHJ1YWtyenRobHl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMzkzMTAsImV4cCI6MjA1OTYxNTMxMH0.csyypsA804XnPjXI1D3D7g61acl02nEX3sYAeYU72Nw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);