// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqsphjwjqhmqyoqzgrgj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xc3BoandqcWhtcXlvcXpncmdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMTQ5NTAsImV4cCI6MjA1OTY5MDk1MH0.blVa8XVL9F5gDObRMg3WNauYxTcvfYJ5AZhHpmUCWE0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);